export const ThesisTerminology = {
  THESIS_1: {
    LABEL: 'Giảng viên hướng dẫn',
    FIELD_NAME: 'lecturers'
  },
  THESIS_2: {
    LABEL: 'Sinh viên thực hiện',
    FIELD_NAME: 'students'
  },
  THESIS_3: 'Danh sách khóa luận',
  THESIS_4: 'Chi tiết khóa luận',
  THESIS_5: 'Các cá nhân liên quan',
  THESIS_6: 'Danh sách giảng viên tham gia',
  THESIS_7: 'Danh sách sinh viên tham gia',
  THESIS_8: 'Xem thêm',
  THESIS_9: 'Thông tin về khóa luận',
  THESIS_10: 'Tiêu đề',
  THESIS_11: 'Người tạo',
  THESIS_12: 'Thời gian bắt đầu',
  THESIS_13: 'Thời gian kết thúc',
  THESIS_14: 'Hạn chót giảng viên đăng ký đề tài',
  THESIS_15: 'Hạn chót sinh viên đăng ký đề tài',
  THESIS_16: 'Hạn chót báo cáo tiến độ',
  THESIS_17: 'Hạn chót phản biện',
  THESIS_18: 'Hạn chót bảo vệ',
  THESIS_19: 'Giai đoạn hiện tại',
  THESIS_20: 'Trạng thái',
  THESIS_21: 'Bạn có muốn xóa khóa luận này?',
  THESIS_22: 'Thao tác này không thể phục hồi.',
  THESIS_23: 'Xác nhận',
  THESIS_24: 'Hủy',
  THESIS_25: 'Tạo khóa luận',
  THESIS_26: 'Sửa khóa luận',
  THESIS_27: 'Khóa luận',
  THESIS_28: 'Ngưng kích hoạt',
  THESIS_29: 'Kích hoạt',
  THESIS_30: 'Vui lòng nhập tiêu đề!',
  THESIS_31: 'Thời gian diễn ra',
  THESIS_32: 'Vui lòng nhập thời gian diễn ra!',
  THESIS_33: 'Vui lòng nhập hạn chót giảng viên đăng ký đề tài!',
  THESIS_34: 'Vui lòng nhập hạn chót sinh viên đăng ký đề tài!',
  THESIS_35: 'Vui lòng nhập hạn chót báo cáo tiến độ!',
  THESIS_36: 'Vui lòng nhập hạn chót phản biện!',
  THESIS_37: 'Vui lòng nhập hạn chót bảo vệ!',
  THESIS_38: 'Bạn có chắc muốn kích hoạt khóa luận này?',
  THESIS_39: 'Bạn có chắc muốn ngưng kích hoạt khóa luận này?',
  THESIS_40: 'Mọi hoạt động của khóa luận này sẽ vô hiệu lực.',
  THESIS_41: 'Mọi hoạt động của khóa luận này sẽ có hiệu lực.',
  THESIS_42: 'Danh sách đề tài'
};
