export const ProgressReportTerminology = {
  PR_1: 'Báo cáo tiến độ',
  PR_2: 'Thời gian',
  PR_3: 'Địa điểm',
  PR_4: 'Ghi chú',
  PR_5: 'Sinh viên báo cáo',
  PR_6: 'Giảng viên hướng dẫn',
  PR_7: 'Người tạo khóa luận',
  PR_8: 'Chỉnh sửa',
  PR_9: 'Chỉnh sửa báo cáo tiến độ',
  PR_10: 'Tài liệu báo cáo',
  PR_12: 'Kết quả',
  PR_13: 'Cho phép phản biện',
  PR_14: 'Dừng phát triển',
  PR_15: 'Chưa có',
  PR_16: 'Bạn có chắc muốn thay đổi kết quả của báo cáo tiến độ này?',
  PR_17: 'Xác nhận',
  PR_18: 'Hủy',
  PR_19: 'Thay đổi kết quả thành công.',
  PR_20: 'Không có dữ liệu báo cáo tiến độ',
  PR_21: 'Chỉnh sửa báo cáo tiến độ thành công',
  PR_22: 'Tài liệu báo cáo không thể thay đổi nếu báo cáo tiến độ đã có kết quả.'
};
