export const TopicTerminology = {
  TOPIC_1: 'Tạo đề tài',
  TOPIC_2: 'Tiêu đề',
  TOPIC_3: 'Mô tả',
  TOPIC_4: 'Tiêu đề là thông tin bắt buộc.',
  TOPIC_5: 'Số lượng sinh viên thực hiện',
  TOPIC_6: 'Danh sách đề tài',
  TOPIC_7: 'Giảng viên hướng dẫn',
  TOPIC_8: 'Trạng thái phê duyệt',
  TOPIC_9: 'Trạng thái đăng ký',
  TOPIC_10: 'Ngày tạo',
  TOPIC_11: 'Chi tiết đề tài',
  TOPIC_12: 'Thông tin đề tài',
  TOPIC_13: 'Thông tin phê duyệt',
  TOPIC_14: 'Người phê duyệt',
  TOPIC_15: 'Lịch sử',
  TOPIC_16: 'Sửa đề tài',
  TOPIC_17: 'Bạn có chắc muốn xóa đề tài này?',
  TOPIC_18: 'Thao tác này không thể phục hồi.',
  TOPIC_19: 'Xác nhận',
  TOPIC_20: 'Hủy',
  TOPIC_21: 'Ghi chú...',
  TOPIC_22: 'Chấp nhận',
  TOPIC_23: 'Từ chối',
  TOPIC_24: 'Trả lại',
  TOPIC_25: 'Mới',
  TOPIC_26: 'Thu hồi',
  TOPIC_27: 'Xác nhận',
  TOPIC_28: 'Đang được phê duyệt',
  TOPIC_29: 'Hủy bỏ',
  TOPIC_30: 'Yêu cầu phê duyệt',
  TOPIC_31: 'Bạn chắc chắn?',
  TOPIC_32: 'Mở đăng ký',
  TOPIC_33: 'Đóng đăng ký',
  TOPIC_34: 'Bạn có chắc muốn mở đăng ký đề tài?',
  TOPIC_35: 'Sinh viên có thể đăng ký đề tài sau khi thao tác này được thực hiện thành công.',
  TOPIC_36: 'Bạn có chắc muốn đóng đăng ký đề tài?',
  TOPIC_37: 'Sinh viên không thể đăng ký đề tài sau khi thao tác này được thực hiện thành công.',
  TOPIC_38: 'Đăng ký đề tài',
  TOPIC_39: 'Bạn chắc chắn muốn đăng ký đề tài này?',
  TOPIC_40:
    'Bạn không thể đăng ký đề tài nào khác cho đến khi giảng viên hướng dẫn đề tài này từ chối.',
  TOPIC_41: 'Trạng thái sinh viên đăng ký',
  TOPIC_42: 'Ngày đăng ký',
  TOPIC_43: 'Phê duyệt đăng ký thành công.',
  TOPIC_44: 'Thao tác thành công.',
  TOPIC_45: 'Đăng ký đề tài thành công.',
  TOPIC_46: 'Danh sách sinh viên đăng ký đề tài',
  TOPIC_47: 'Mở đăng ký đề tài thành công.',
  TOPIC_48: 'Đóng đăng ký đề tài thành công.',
  TOPIC_49: 'Bạn có chắc muốn chấp nhận sinh viên này?',
  TOPIC_50: 'Bạn có chắc muốn từ chối sinh viên này?',
  TOPIC_51: 'Số lượt đăng ký',
  TOPIC_52: 'Số lượng sinh viên được chấp nhận',
  TOPIC_53: 'Còn trống',
  TOPIC_54: 'Đề tài'
};
