name: CD-production

on:
  push:
    branches: [master]

jobs:
  heroku:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "grasis-api"
          heroku_email: "nguyenduypoon@gmail.com"
          appdir: "api"