name: CD

on:
  push:
    branches: [ 1.0.0 ]
  pull_request:
    branches: [ 1.0.0 ]

jobs:
  heroku:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_DEV_APP}}
          heroku_email: $GITHUB_ACTOR
          appdir: "api"